export class Constants {
business_types:Array < any> = ['Abattoirs' ,
'Accountants' ,
'Administration Services' ,
'Adventure Activity' ,
'Advertising-Point of Sale ' ,
'Agricultural Contractors   ' ,
'Agricultural Merchants ' ,
'Agricultural Supplies  ' ,
'Air Conditioning ' ,
'Ambulance Service   ' ,
'Amusement Centres/Leisure Attractions  ' ,
'Animal Supplies' ,
'Animal Welfare Societies    ' ,
'Antique Dealers' ,
'Antique Repair and Restoration' ,
'Architects ' ,
'Architectural Technologists and Technicians    ' ,
'Aromatherapy   ' ,
'Art and Craft Eqpt and Materials' ,
'Art and Craft Shops    ' ,
'Assessors  ' ,
'Auctioneers and Valuers    ' ,
'Bacon and Ham Curers and Suppliers    ' ,
'Bakers and Mfrg and Wh andsale    ' ,
'Bakers and Confectioners-Retail    ' ,
'Banks and Financial Institutions    ' ,
'Bathroom Showroom    ' ,
'Batteries/Accumulators ' ,
'Beauty Treatments' ,
'Bed and Breakfast' ,
'Bespoke Software Development and Solutions' ,
'Blacksmiths and Forgemasters' ,
'Boat Hire ' ,
'Boat Sales' ,
'Boat Trips and Cruises ' ,
'Booksellers' ,
'Books-Rare and Secondhand' ,
'Broadband Services ' ,
'Builders' ,
'Builders and Merchants' ,
'Buildings-Sectional' ,
'Bulk Handling ' ,
'Burglar Alarms' ,
'Bus and Coach Services' ,
'Business Enterprise Agencies' ,
'Business Finance' ,
'Business Information Providers' ,
'Butchers' ,
'Cable Manufacturers and Suppliers' ,
'Cafes' ,
'Camping Eqpt' ,
'Camping Sites' ,
'Canal Boat Trips' ,
'Candles ' ,
'Canine Feeds' ,
'Car and Commercial Vehicle Dismantlers' ,
'Car Accessory Mfrs' ,
'Car and Motor Cycles MOTs' ,
'Car Body Repairs ' ,
'Car Breakdown Recovery' ,
'Car Dealers and Distributors' ,
'Car Parts' ,
'Car Servicing and Repairs' ,
'Caravan Parks-Holiday' ,
'Careers Services ' ,
'Carpenters and Joiners ' ,
'Caterers ' ,
'Catering Supplies-Food and Drink ' ,
'Cement and Fibre Manufacturing' ,
'Central Heating Services-Domestic' ,
'Ceramics' ,
'Chambers of Commerce ' ,
'Charity Shops ' ,
'Chemical Engineers and Consultants' ,
'Chemical Suppliers' ,
'Chemists-Dispensing' ,
'Childrens Play Equipment' ,
'Cinemas' ,
'Cladding' ,
'Cleaning and Maintenance Services' ,
'Clinics ' ,
'Clothes Shops and Ladies' ,
'Clothes Shops and Men ands ' ,
'Clothing Mfrs and Wh andsalers' ,
'Coach Hire' ,
'Collectors and Items and Curios' ,
'Commercial Investigations' ,
'Commercial Vehicle Dealers' ,
'Commercial Vehicle Repairs ' ,
'Community Centres ' ,
'Complementary Therapies' ,
'Computer Consumables' ,
'Computer Maintenance' ,
'Computer Network Installation and Maintainance' ,
'Computer Services ' ,
'Computer Upgrades, Repair, Maintenance' ,
'Concrete-Ready-Mixed ' ,
'Confectionary Retailer ' ,
'Confectionery Mfrs and Wh andsalers' ,
'Conference Facilities and Services' ,
'Conference Organisers' ,
'Conservation Organisations ' ,
'Construction' ,
'Consultants' ,
'Cooked Meat Mfrs and Wh andsalers' ,
'Co-Operative Societies ' ,
'Corporate Entertainment ' ,
'Counselling and Advice' ,
'Courier Services' ,
'Curtains ' ,
'Cycle Hire ' ,
'Cycle Shops' ,
'D I Y Stores' ,
'Dairy Farmers' ,
'Day Nurseries ' ,
'Debt Collectors' ,
'Decking' ,
'Delicatessens' ,
'Delivery and Collection Services' ,
'Dental Surgeons' ,
'Dental Technicians ' ,
'Designers-Advertising and Graphic' ,
'Detective Agencies' ,
'Digital and Traditional Photo Processing' ,
'Discos and Mobile ' ,
'Doctors Medical Practitioners ' ,
'Dog Breeders' ,
'Dolls and Dolls and Houses' ,
'Drain and Pipe Cleaning' ,
'Drapery Retailers' ,
'Dressmakers' ,
'Driving Schools' ,
'Dry Cleaners ' ,
'e commerce' ,
'Egg Merchants ' ,
'Electrical Appliance Retailers ' ,
'Electrical Engineers' ,
'Electricians and Electrical Contractors ' ,
'Electromedical Apparatus ' ,
'Electronic Components ' ,
'Employment Agencies and Consultants ' ,
'Engineers-Design and Development ' ,
'Enterprise Trusts' ,
'Environmental Consultants' ,
'Estate Agents' ,
'Event / Festival trader' ,
'Executive Search and Selection' ,
'Exhibition and Show Organisers' ,
'Exhibitions' ,
'Fancy Dress' ,
'Farm Buildings and Eqpt' ,
'Farmers' ,
'Fibre Optics' ,
'Financial Advisers' ,
'Fire Alarms' ,
'Fire Protection Engineers' ,
'Firework Sales' ,
'Fish and Chip Shops and Restaurants' ,
'Fishing Tackle Shops ' ,
'Flooring ' ,
'Florists' ,
'Florists and Supplies' ,
'Food Mfrs and Suppliers ' ,
'Food Processing Machinery' ,
'Forestry Consultants' ,
'Formwork and Shuttering' ,
'Forwarding Agents ' ,
'Funeral Directors ' ,
'Furnaces-Industrial' ,
'Furniture Mfrs and Designers' ,
'Furniture Repair and Restoration' ,
'Furniture Retailers' ,
'Gallery' ,
'Garage Services  ' ,
'Garden Eqpt Mfrs and Wh andsalers' ,
'Garden Furniture and Ornaments ' ,
'Garden Maintenance' ,
'Gates and Fencing ' ,
'Gift Shops' ,
'Glass Workers' ,
'Golf Clubs, Courses and Professionals ' ,
'Government Support Agencies ' ,
'Graphic Design' ,
'Greengrocers and Fruit Sellers' ,
'Greetings Cards' ,
'Grocers and Convenience Stores' ,
'Groundwork Contractors' ,
'Guest Houses' ,
'Hairdressers and Beauty Supplies' ,
'Hairdressers-Ladies and' ,
'Hairdressers-Men ands' ,
'Hardware Retailers' ,
'Hay and Straw Merchants' ,
'Health and Safety Consultants' ,
'Health Food Shop' ,
'Healthcare and Hygiene services' ,
'Heating Eqpt-Gas' ,
'Herbalists ' ,
'Historic Buildings and Stately Homes' ,
'Holiday Accommodation' ,
'Holistic Therapies' ,
'Horse Drawn Carriages ' ,
'Hospitals' ,
'Hotels and Inns' ,
'House Staging Service' ,
'Household Stores' ,
'Housing Associations and Trusts' ,
'Hydraulic Engineers ' ,
'Hydraulic Plant and Eqpt Mfrs' ,
'Illustrator' ,
'Import/Export' ,
'Independent Financial Advisers' ,
'Institutes ' ,
'Insurance Agents' ,
'Insurance Companies ' ,
'Insurance Services and Administration' ,
'Interior Designers' ,
'Internet Café' ,
'Internet Services ' ,
'Internet Web Design' ,
'Jewellers' ,
'Joinery Mfrs' ,
'Keycutting' ,
'Kitchen Eqpt' ,
'Kitchen Planning and Installation' ,
'Knitwear Retailers ' ,
'Landscapers' ,
'Launderettes' ,
'Legal Services' ,
'Leisure Centres' ,
'Libraries' ,
'Licenced Trade Specialists' ,
'Local Government' ,
'Local Produce' ,
'Management and Business Consultants' ,
'Marble and Granite Fabricators' ,
'Marketing and Advertising Consultants' ,
'Metal Casting' ,
'Metal Fabrication' ,
'Model Mfrs-Toys and Hobbies' ,
'Model Shops ' ,
'Mortgage Advice' ,
'Motor Cycle Dealers' ,
'Motor Cycle Engineers' ,
'Motor Cycle Training and Testing' ,
'Musical Instrument Manufacture and Repair' ,
'Needlecraft Retailers ' ,
'Newsagents' ,
'Newspapers and Magazines' ,
'Notaries' ,
'Nurseries-Horticultural-Retail' ,
'Nursery Play Equipment' ,
'Nurses and Agencies and Care Agencies ' ,
'Nursing Homes' ,
'Off Licences and Wine Merchants' ,
'Office Machinery' ,
'Oil Heating' ,
'Organic Food ' ,
'Outdoor Equipment and Clothing' ,
'Outdoor Pursuits ' ,
'Packaging ' ,
'Painters and Decorators' ,
'Party Decorations' ,
'Payroll Services' ,
'Personalised gifts ' ,
'Pest Control' ,
'Pet Portraits' ,
'Petrol Filling Stations' ,
'Pharmaceutical Products Mfg' ,
'Photographers-Commercial and Industrial' ,
'Photographers-General ' ,
'Picture Framers and Frame Makers ' ,
'Pine and Cane Furniture' ,
'Places of Worship' ,
'Plant and Machinery Hire ' ,
'Plastering and Screeding' ,
'Plumbers' ,
'Plumber ands Merchants' ,
'Political Organisations' ,
'Pollution Control ' ,
'Post Offices' ,
'Precision Engineering ' ,
'Predictive Maintenance ' ,
'Printers and Lithographers' ,
'Printers and Supplies' ,
'Printing-Stationery ' ,
'Private Investigators' ,
'Property Development ' ,
'Public Houses ' ,
'Public Relations Consultants ' ,
'Publishers and Services' ,
'Quantity Surveyors' ,
'Quarries' ,
'Race Courses' ,
'Railway Stations and Offices' ,
'Recruitment Consultants' ,
'Religious Organisations ' ,
'Removals and Storage' ,
'Residential and Retirement Homes' ,
'Restaurants ' ,
'Riding Schools' ,
'Road Haulage Services' ,
'Roller Shutter' ,
'Roller, Shutter and Garage Doors' ,
'Roofing Services ' ,
'Salvage and Reclamation' ,
'Sandwich Shops and Delivery ' ,
'Satellite and High Gain Aerials' ,
'Sawmills ' ,
'Schools and Colleges' ,
'schools/colleges' ,
'Scrap Metal Merchants' ,
'Security Services and Equipment' ,
'Share Dealers' ,
'Shoe Shops' ,
'Shopping Centres' ,
'Sign Makers' ,
'Sign Writers ' ,
'Solicitors' ,
'Sound Equipment' ,
'Sound Equipment Hire' ,
'Spares' ,
'Special NeedsEquipment' ,
'Sports and Social Complex' ,
'Sports Equipment and Clothing' ,
'Stained Glass Artists' ,
'Steel Works ' ,
'Stone Mason ' ,
'Supermarkets' ,
'Surveyors and Valuers ' ,
'Take Away Food' ,
'Taxidermists' ,
'Taxis and Private Hire Vehicles' ,
'Teddy Bear Repairs' ,
'Teddy Bear Specialist' ,
'Tent and Marquee Hire' ,
'Textiles ' ,
'Theatres and Concert Halls' ,
'Therapists' ,
'Thermometers' ,
'Timber Merchants' ,
'Toiletries/Cosmetics' ,
'Tourist Attractions' ,
'Tourist Information Centres' ,
'Toy and Game Mfrs and Importers ' ,
'Toy Shops' ,
'Trailer Eqpt Mfrs' ,
'Trailer Hire' ,
'Training Services' ,
'Translation and Interpretation' ,
'Travel Agents and Tour Operators' ,
'Travel Companions' ,
'Tree Work' ,
'Trophies, Medals and Rosettes' ,
'Tutoring' ,
'Tv and Video Rental' ,
'Tv, Video and Radio Shops' ,
'Tyre Distributors and Dealers' ,
'Unclassified' ,
'Unisex Hairdressers' ,
'Universities/Polytechnics' ,
'Upholsterers' ,
'Vacuum Engineering and Eqpt' ,
'Vegetarian Food' ,
'Vehicle Electrical Retailer ' ,
'Vending Machines' ,
'Veterinary Surgeons' ,
'Video Tapes-Hire and Retail ' ,
'Water Sports' ,
'Waterproofing for roofs, floors and walls' ,
'Web Design' ,
'Wedding Services and Eats and Drinks' ,
'Windmills and Windpower Eqpt' ,
'Windscreen Services' ,
'Wine Bars' ,
'Wine Producers and Vineyards' ,
'Wire Goods' ,
'Wire Manufacturers ' ,
'Wool Shops' ,
'Word Processing Services' ,
'Workwear' ,
];


}
